### ISSUE TITLE
[SW5] Credit Card Payment impossible with Shopware Version 5.7.6

### ISSUE THREAD

**Issue by florianfaatz** [pickware/ShopwareStripePayment#106]
**How does the system behave currently?**

Under Shopware 5.7.6 and Stripe Plugin Version 5.4.1, the fields _Card Number_, _Valid until_ and _CVC_ are not shown when selecting credit card as payment method. The problem persists after emptying the caches and compiling themes multiple times and changing browser for the frontend. 

![image](https://user-images.githubusercontent.com/46442425/140303165-67845b3c-0036-4b62-9c6a-96c8673e8f73.png)

**How should the system behave?**

The fields should be displayed and fillable in the frontend.

**Comment by JanRogge** [comment]
After setting the Stripe credentials and clearing the cache and theme again everything seems to work fine in your test setup. And it also works locally with 5.7.6. 

Because of this i will close this Issue.

<img width="1203" alt="Bildschirmfoto 2021-11-08 um 13 34 33" src="https://user-images.githubusercontent.com/11475491/140742976-4a0e671e-9bc4-44da-a74b-e12f0e298fc7.png">
