### ISSUE TITLE
Add support for Klarna

### ISSUE THREAD

**Issue by svenmuennich** [pickware/ShopwareStripePayment#59]
Documentation can be found [here](https://stripe.com/docs/sources/klarna).

**Comment by JanRogge** [comment]
There are a few things that need to be added to the Documentation for Klarna as a payment method.

- The Stripe Documentation about Klarna mentions that you need to update your Terms and Conditions as a [prerequisite](https://stripe.com/docs/sources/klarna#prerequisite).

- Also since Klarna only Supports a few countries and only one currency for each country the payment method needs to be configured to only allow Klarna for these countries and that the corresponding currency for the countries is also available.

**Comment by jessicapleier** [comment]
Doku:
https://docs.google.com/document/d/1FfZU0AqEWtiXd7Ito6e7UiLzfpP5F_D8CT9gtogaZlk/edit#heading=h.k7nf0vot930m

**Comment by JanRogge** [comment]
This was released in `v5.3.0`.
